name: Build and Test

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }} # compiles and test on Ubuntu

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ["1.8"]
      fail-fast: false

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    # Java JDK 11 used for maven build
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64

    # Try to find and apply jbosstools cache
    - name: Cache local Maven repository for JBoss Tools components
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: jboss-stacks-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          jboss-stacks-${{ runner.os }}-maven-

    # Build and compile using Maven
    - name: Build/Compile and run unit tests
      run: mvn verify -B --no-transfer-progress

    # Archive artifacts to be applied in Publish Reports workflow
    - name: Archiving test artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with: 
        name: ${{ matrix.os }}-test-reports
        path: |
          target/surefire-reports/
